name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - name: Clone repository recursively
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.*'
        cache: 'true'
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
              -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX='../install' ..
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --target install
    - name: Deploy Windows
      run: |
        windeployqt.exe --release --compiler-runtime --dir launcher_deploy install/bin/SM64APLauncher
        cp -r presets/ launcher_deploy
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SM64AP-Launcher_windows
        path: |
          launcher_deploy/*
  
  build-lin:
    name: Build (ubuntu-latest)

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository recursively
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.*'
        cache: 'true'
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX='/usr' ..
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --target install DESTDIR=AppDir
    - name: Install linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1.7.0
      with:
        plugins: qt appimage
    - name: Install AppImage dependencies
      run: |
        sudo apt update && sudo apt install appstream libfuse2
    - name: Create AppImage
      run: |
        cd build
        linuxdeploy-x86_64.AppImage --appdir AppDir --desktop-file=../res/SM64APLauncher.desktop --icon-file=../res/icon.png --output appimage
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SM64AP-Launcher_linux
        path: |
          build/SM64AP_Launcher-x86_64.AppImage
