name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - name: Clone repository recursively
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.*'
    - name: CMake configure (default version)
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
              -DUSE_ZLIB=OFF `
              -DCMAKE_BUILD_TYPE=Release ..
    - name: Build (default version)
      run: |
        cd build
        cmake --build . --config Release
    - name: Create Artifact Folder
      run: |
        mkdir artifact
        copy build/* artifact
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: _dev_SM64AP-Launcher
        path: |
          artifact/*
