name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - name: Clone repository recursively
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.*'
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
              -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX='../install' ..
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --target INSTALL
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: _dev_windows_SM64AP-Launcher
        path: |
          install/*
  
  build-lin:
    name: Build (ubuntu-latest)

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository recursively
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.*'
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX='../install' ..
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --target INSTALL
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: _dev_linux_SM64AP-Launcher
        path: |
          install/*
